stages:
  - integration

# Cache libraries in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

phpunit:
  stage: integration
  image: wordpress:4.9.8-php7.1
  script:
    - apt-get update -yqq
    - apt-get install git -yqq # Install git, the php image doesn't have installed
    - apt-get -yqqf install vim wget zip unzip subversion mysql-client libmcrypt-dev --fix-missing # instll the required packages for the running CI tests.
    - curl -sS https://getcomposer.org/installer | php # Install composer
    - php composer.phar install # Install all project dependencies
    - "docker stop $(docker ps -a -q)"
    - composer wp:install
    - composer wp:tests
