version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8228:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DEBUG: 1
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - .:/var/www/html/wp-content/plugins/caldera-forms

  cli:
    image: wordpress:cli
    volumes:
    - wordpress:/var/www/html
    - .:/var/www/html/wp-content/plugins/caldera-forms
    - ./wp-content/plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test

  wordpress_phpunit:
    image: chriszarate/wordpress-phpunit
    environment:
      PHPUNIT_DB_HOST: mysql
    volumes:
      - .:/app
      - testsuite:/tmp

  composer:
    image: composer
    volumes:
      - .:/app
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: cypress/browsers:chrome67
    depends_on:
      - wordpress
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://sentimentalyzer:8123
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - ./:/e2e
volumes:
  testsuite:
  wordpress:
