name: PHP Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.0'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install

    - name: Install js packages
      run: yarn

    - name: Refresh assets build
      run: yarn build

    - name: Install wordpress
      run: composer wp:install

    - name: Activate Caldera Forms
      run: composer wp:activate

    - name: Tests setup
      run: composer test:setup

    - name: Run test unit
      run: composer test:unit

    - name: Run test wp
      run: composer wp:tests
